name: dev instance workflow

on: push

jobs:
  dev-deployment: 
    name: "dev deployment"
    runs-on: ubuntu-latest

    steps:
    - name: "clone code respo"
      uses: actions/checkout@v4
    - name: "print message"
      run: echo "cloned the repo"
    